name: "CI"

on:
  push:
    branches: [master]
  merge_group:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=8192"

jobs:
  astrocheck:
    name: Check for type issues with astro check
    runs-on: ubuntu-24.04
    env:
      FORCE_COLOR: true
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run Check
        run: bun run check
  eslint:
    name: Check for code issues with ESLint
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run Check
        run: bun run lint:eslint

  build:
    name: Build the project
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Run Build
        run: bun run build
