name: "Write coauthors to a pull request"

permissions:
  pull-requests: write

on:
  issue_comment:
    types:
      - created

jobs:
  generate-coauthors:
    name: Generate Coauthor
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: kevinzunigacuellar/coauthor-action@v0.1.3
